goalGrove/community/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'community'

urlpatterns = [
    path('', community_view, name='community'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goalGrove/goalGrove/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import login_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_view, name='login'),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('goals/', include('goals.urls')),
    path('reviews/', include('reviews.urls')),
    path('qna/', include('qna.urls')),
    path('community/', include('community.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goalGrove/goals/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'goals'

urlpatterns = [
    path('create/', create_goal, name='create_goal'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goalGrove/posts/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('create/', create_post, name='create_post'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goalGrove/qna/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'qna'

from django.urls import path
from . import views

urlpatterns = [
    path('questions/create/', create_question, name='create_question'),
    path('questions/delete/<int:question_id>/', delete_question, name='delete_question'),
    path('questions/answer/create/', create_answer, name='create_answer'),
    path('', get_questions, name='get_questions'),
]

goalGrove/users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('main/', main_view, name='main'),
    path('shop/', shop_view, name='shop'),
    path('shop/review', review_view, name="review"),
    path('shop/qna', qna_view, name="qna"),
    path('signup/', signup_view, name='signup'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('pwverification/', pwverification_view, name='pwverification'),
    path('pwreset/', pwreset_view, name='pwreset'),
]

goalGrove/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(max_length=30, unique=True, null=False, blank=False)
    nickname = models.CharField(max_length=20, unique=True)
    username = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return f'{self.username}'

goalGrove/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'nickname']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'nickname': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(label='새 비밀번호', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='새 비밀번호 확인', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password and confirm_password:
            if new_password != confirm_password:
                raise forms.ValidationError("새 비밀번호와 비밀번호 확인이 일치하지 않습니다.")
        
        return cleaned_data

goalGrove/users/views.py
from django.shortcuts import render, redirect, get_object_or_404 
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import SignUpForm, ResetPasswordForm
from django.views.decorators.csrf import csrf_exempt
import json
from posts.models import Category, Post
from goals.models import GCategory, Goal
User = get_user_model()

@login_required
def main_view(request):
    user = request.user
    categories = Category.objects.all()
    category_id = request.GET.get('category')
    gcategories = GCategory.objects.all()
    gcategory_id = request.GET.get('gcategory')
    
    if category_id:
        category = get_object_or_404(Category, id = category_id)
        posts = category.posts.all().order_by('-id')
    else:
        posts = Post.objects.all().order_by('-id')

    if gcategory_id:
        gcategory = get_object_or_404(GCategory, id = gcategory_id)
        goals = gcategory.goals.all().order_by('-id')
    else:
        goals = Goal.objects.all().order_by('-id')

    context = {
        'user_name': user.username,
        'user_email': user.email,
        'categories': categories,
        'gcategories': gcategories,
        'posts': posts,
        'goals': goals,
    }  

    return render(request, 'users/main.html', context)

@login_required
def shop_view(request):
    user = request.user
    context = {
        'user_name': user.username,
        'user_email': user.email,
    }
    return render(request, 'users/shopping.html', context)

@login_required
def review_view(request):
    user = request.user
    context = {
        'user_name': user.username,
        'user_email': user.email,
    }
    return render(request, 'reviews/review.html', context)

@login_required
def qna_view(request):
    user = request.user
    context = {
        'user_name': user.username,
        'user_email': user.email,
    }
    return render(request, 'qna/qna.html', context)

def signup_view(request):
    if request.method == "GET":
        form = SignUpForm()
        return render(request, 'users/signup.html', {'form': form})
    
    elif request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, '회원가입이 완료되었습니다.')
            return redirect('login')
        else:    # 회원가입 폼이 유효하지 않은 경우
            return render(request, 'users/signup.html', {'form': form})

    else:    # GET 또는 POST 요청 외의 다른 메소드는 처리하지 않음
        return render(request, 'users/signup.html')

def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            auth_login(request, user)
            return redirect('users:main')  # main 페이지로
        else:
            error_message = "아이디 또는 비밀번호가 올바르지 않습니다."
            return render(request, 'users/login.html', {'error_message': error_message})
    else:
        return render(request, 'users/login.html')

def pwverification_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')

        user = User.objects.filter(username=username, email=email).first()
        if user:
            request.session['reset_user_id'] = user.id  # 세션에 사용자 ID 저장
            return redirect('users:pwreset')
        else:
            return HttpResponse('아이디와 이메일이 일치하지 않습니다.', status=400)
    return render(request, 'users/pwverification.html')

def pwreset_view(request):
    user_id = request.session.get('reset_user_id')
    user = get_object_or_404(User, pk=user_id)

    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data['new_password']

            # 비밀번호 변경
            user.set_password(new_password)
            user.save()

            # 세션 초기화
            del request.session['reset_user_id']

            messages.success(request, '비밀번호가 성공적으로 변경되었습니다.')
            return redirect('users:login')
        else:
            # 폼이 유효하지 않은 경우
            return render(request, 'users/pwreset.html', {'form': form})
    else:
        form = ResetPasswordForm()
        return render(request, 'users/pwreset.html', {'form': form})

goalGrove/users/templates/users/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoalGrove 로그인</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css">
    <link rel="stylesheet" href="{% static 'css/loginstyles.css' %}">
</head>
<body>
    <div class="container"
        data-hideicon-url="{% static 'img/hideicon.svg' %}" 
        data-showicon-url="{% static 'img/showicon.svg' %}">
        <div class="logo-container">
            <img src="{% static 'img/logo_shadow.svg' %}" alt="GoalGrove 로고" class="logo">
            <p class="description">
                <span>GoalGrove</span>에서 목표를 세우고 공유하며<br>주체적 성장을 시작하세요.
            </p>
        </div>
        <div class="main-content">
            <div class="login-container">
                <h2>로그인</h2>
                <form id="loginForm" method="POST" novalidate>
                    {% csrf_token %}
                    <label for="username">아이디를 입력하세요.</label>
                    <input type="text" name="username" id="username" required>
                    <div class="password-container">
                        <label for="password">비밀번호를 입력하세요.</label>
                        <img src="{% static 'img/hideicon.svg' %}" alt="Hide" class="hide-icon" id="togglePassword">
                    </div>
                    <input type="password" name="password" id="password" required>
                    <button type="submit">로그인하기</button>
                </form>
                {% if error_message %}
                    <div class="error-message">{{ error_message }}</div>
                {% endif %}
                <a href="{% url 'users:pwverification' %}" class="forgot-password">비밀번호찾기</a>
            </div>
            <div class="signup-container">
                <p class="signup">
                    GoalGrove를 처음 사용하시나요? <a href="{% url 'users:signup' %}">회원가입하기</a>
                </p>
            </div>
        </div>
    </div>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

goalGrove/users/templates/users/main.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Main</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}" />
  </head>
  <body>
    <div class="Wrapper">
      <div class="navBar">
        <button class="menu" id="menuButton"></button>

        <div class="userNav">
          <div class="userNavTxt">
            <div class="userName">{{ user_name }}</div>
            <div class="userEmail">{{ user_email }}</div>
          </div>
          <button class="logout"></button>
        </div>
        <div id="navBarMenuContainer">
          <a href="{% url 'users:main' %}">
            <div class="navBarMenu">
              <img src="{% static 'img/Heart.svg' %}" />
              <span class="menuText">메인</span>
            </div>
          </a>
          <a href="{% url 'users:shop' %}">
            <div class="navBarMenu">
              <img src="{% static 'img/Cart.svg' %}" />
              <span class="menuText">목표쇼핑</span>
            </div>
          </a>
          <a href="{% url 'community:community' %}">
            <div class="navBarMenu">
              <img src="{% static 'img/Group.svg' %}" />
              <span class="menuText">커뮤니티</span>
            </div>
          </a>
        </div>
      </div>
      <div>
        <img
          class="logoTop"
          alt="상단 로고"
          src="{% static 'img/LogoMain.png' %}"
        />
        <!-- 본문 내용 -->
        <div class="Wrapper">
          <!-- 목표 선정 -->
          <div class="goalChoice">
            <!-- 목표 선정 제목 -->
            <div class="Wrapper1">
              <div class="mainTxt">목표 선정</div>
              <!-- 드롭다운 -->

              <button class="goalAdd3">
                <a href="{% url 'goals:create_goal' %}">목표 만들기</a>
              </button>
              <!-- <div class="dropdown-content">
                  <div class="dropdownMain" id="createGoal">목표 만들기</div>
                  <div class="dropdownMain" id="goalCart">목표 장바구니</div>
                </div> -->

              <div class="detailTxt">
                목표를 만들거나 만들어진 목표들을 골라요!
              </div>
            </div>
            <!-- 목표 선정 박스 -->

            <!-- 목표장바구니 -->

            <div class="Wrapper2">
              <div class="goalTxt">목표 장바구니</div>
              <div class="line"></div>
              <div class="Wrapper10">
                <div class="Wrapper6">
                  <div class="goalWrapper">
                    <span class="marketName">말하는 감자</span>
                    <img
                      src="/static/img/X.svg"
                      alt="창 닫기"
                      class="marketX"
                    />
                  </div>
                  <div class="goalWrapper">
                    <div class="marketWrapper">
                      <img
                        src="/static/img/market.svg"
                        alt="장바구니 사진"
                        class="marketImg"
                      />
                      <div class="marketWrapper2">
                        <div class="marketWrapper3">
                          <span class="marketgoalTxt">주 3회 요가</span>
                          <span class="category_content">운동</span>
                        </div>
                        <div class="marketWrapper4">
                          <span class="countTxt_market">일주일에</span>
                          <span class="timeIng_market">3회</span>
                        </div>
                      </div>
                    </div>
                    <div class="marketChoicebtn">선택하기</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- 이루고 있는 목표 -->
          <div class="Wrapper11">
            <!-- 이루고 있는 목표 제목 -->
            <div class="Wrapper1">
              <div class="mainTxt">이루고 있는 목표</div>
              <div class="detailTxt">목표를 얼마나 이루었는지 확인해요!</div>
            </div>
            <!-- 이루고 있는 목표 박스 -->
            <div class="goalingg">
              <div class="Wrapper3">
                {% for goal in goals %}
                <div class="goalWrapper">
                  <span>
                    <span class="goalTxt2">{{ goal.title }}</span>
                    {% comment %} <span class="categoryExp" id="goal-ing-end">종료하기</span> {% endcomment %}
                  </span>
                  <div>
                    {% comment %} <span class="categoryExp">카테고리</span>
                    <div class="dropdownCategory2">
                      {% for category in goal.gcategory.all %}
                      <div class="goalIng-category">{{ goal.category }}</div>
                      {% endfor %}
                    </div> {% endcomment %}
                  </div>
                </div>
                <div class="line2"></div>

                <div style="display: flex; flex-direction: column">
                  <div class="goalDetail2">
                    <div class="goalDetail1">
                      <img
                        src="{% static 'img/goalIng.png' %}"
                        alt="이루고 있는 목표 이미지"
                        class="imgIng"
                      />
                      <div class="countTxt">일주일에</div>
                      <div class="timeIng">{{ goal.frequency }}</div>
                    </div>

                    <div>
                      {% comment %} <div class="detailIcon">
                        <img
                          class="detailIconImg"
                          src="{% static 'img/Line_up.png' %}"
                          alt="성취율 아이콘"
                        />
                        <span class="detailTxt2">성취율</span>
                        <span class="percentage">65%</span>
                      </div>
                      <div class="detailIcon">
                        <img
                          class="detailIconImg"
                          src="{% static 'img/Chart.png' %}"
                          alt="참가자 아이콘"
                        />
                        <span class="detailTxt2">참가자</span>
                        <span class="participant">630명</span>
                      </div> {% endcomment %}
                    </div>
                  </div>
                  <div class="goalIngDetail">
                    {{ goal.content }}
                  </div>
                </div>
                {% endfor %}
              </div>
              
            </div>
          </div>
        </div>


        <!-- 과정 나누기 -->
        <div class="goalChice">
          <!-- 과정 나누기 제목 -->
          <div class="Wrapper7">
            <div class="mainTxt">과정 나누기</div>
            <button class="goalAdd2">
              <a href="{% url 'posts:create_post' %}">과정 나누기 등록</a>
            </button>
            <div class="detailTxt">
              다른 사람들과 목표를 이루는 과정을 나누고 인증해요!
            </div>
          </div>
          <!-- 목표 선정 박스 -->
          <div class="Wrapper12">
            <div class="Wrapper5">
              {% for post in posts %}
              <div class="goalWrapper">
                <div>
                  <span class="goalTxt">{{ post.title }}</span>
                  <span class="processT">{{ post.created_at }}</span>
                </div>
                {% comment %} <div>
                  <span class="categoryExp">카테고리</span>
                  <div class="dropdownCategory3">
                    <div class="goalIng-category">취미</div>
                  </div>
                </div> {% endcomment %}
              </div>
              <div class="line"></div>
              <div class="goalDetail">
                <div class="processContent">
                  <div class="goalTime2">
                    <span class="processTime">
                      {% comment %} <span id="processTime">{{ post }}</span>
                      <span>회차</span> {% endcomment %}
                    </span>
                    {% comment %} <div>
                      <span class="countTxt">일주일에 {{ post.frequency }}</span>
                    </div> {% endcomment %}
                  </div>
                  <!-- 설명 -->
                  <div class="processExplain">
                    <div>
                      {{ post.content }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

goalGrove/users/templates/users/pwreset.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>비밀번호 재설정</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/loginstyles.css' %}">
</head>
<body>
    <div class="container">
        <div class="logo-container">
            <img src="{% static 'img/logo_shadow.svg' %}" alt="GoalGrove 로고" class="logo">
            <p class="description">
                <span>GoalGrove</span>에서 목표를 세우고 공유하며<br>주체적 성장을 시작하세요.
            </p>
        </div>
        <div class="main-content">
            <div class="reset-container">
                <h2>비밀번호 재설정</h2>
                <form id="resetForm" method="post" action="{% url 'users:pwreset' %}" novalidate>
                    {% csrf_token %}
                    <label for="new_password">새 비밀번호</label>
                    <input type="password" name="new_password" id="new_password" required>
                    <label for="confirm_password">새 비밀번호 확인</label>
                    <input type="password" name="confirm_password" id="confirm_password" required>
                    <div id="resetErrorMessage" class="error-message"></div>
                    <button type="submit">비밀번호 재설정</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

goalGrove/users/templates/users/pwverification.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>비밀번호 재설정 - 인증</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/loginstyles.css' %}">
</head>
<body>
    <div class="container">
        <div class="logo-container">
            <img src="{% static 'img/logo_shadow.svg' %}" alt="GoalGrove 로고" class="logo">
            <p class="description">
                <span>GoalGrove</span>에서 목표를 세우고 공유하며<br>주체적 성장을 시작하세요.
            </p>
        </div>
        <div class="main-content">
            <div class="verification-container">
                <h2>비밀번호 재설정</h2>
                <form id="verificationForm" method="post" action="{% url 'users:pwverification' %}" novalidate>
                    {% csrf_token %}
                    <label for="username">아이디</label>
                    <input type="text" name="username" id="username" required>
                    <label for="email">이메일</label>
                    <input type="email" name="email" id="email" required>
                    <div id="verificationErrorMessage" class="error-message"></div>
                    <button type="submit">확인</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

goalGrove/users/templates/users/shopping.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Shopping</title>

    <link rel="stylesheet" href="{% static 'css/shoppingstyle.css' %}" />
    <script src="{% static 'js/shopping.js' %}"></script>
  </head>
  <body>
    <div class="Wrapper">
      <div class="navBar">
        <button class="menu" id="menuButton"></button>
        <div class="userNav">
          <div class="userNavTxt">
            <div class="userName">{{ user_name }}</div>
            <div class="userEmail">{{ user_email }}</div>
          </div>
          <button class="logout"></button>
        </div>
        <div id="navBarMenuContainer">
          <a href="{% url 'users:main' %}">
            <div class="navBarMenu">
              <img src="{% static 'img/Heart.svg' %}" />
              <span class="menuText">메인</span>
            </div>
          </a>
          <a href="{% url 'users:shop' %}">
            <div class="navBarMenu">          
              <img src="{% static 'img/Cart.svg' %}" />
              <span class="menuText">목표쇼핑</span>
            </div>
          </a>
          <a href="{% url 'community:community' %}">
            <div class="navBarMenu">
              <img src="{% static 'img/Group.svg' %}" />
              <span class="menuText">커뮤니티</span>
            </div>
          </a>
        </div>
        </div>
      </div>
    </div>
    <div class="Wrapper2">
      <img class="logoTop" alt="상단 로고" src="{% static 'img/LogoMain.png' %}" />
    <div class="content">
      <div class="title"><h1>목표 쇼핑</h1></div>
      <div class="category-buttons">
        <button onclick="filterCategory('all')">전체</button>
        <button onclick="filterCategory('exercise')">운동</button>
        <button onclick="filterCategory('diet')">식단</button>
        <button onclick="filterCategory('study')">공부</button>
        <button onclick="filterCategory('hobby')">취미</button>
        <button onclick="filterCategory('habit')">습관</button>
        <button onclick="filterCategory('self')">자기계발</button>
        <button class="forGrove-btn" onclick="filterCategory('forGrove')">
          forGrove
        </button>
      </div>
      <div id="goals-container">
        <div class="goal-card" data-category="운동">
          <div class="goal-header">
            <div class="logo-background">
              <img src="{% static 'img/asset/Logo2 1.svg' %}" alt="Goal Icon" />
            </div>
            <div class="goal-nickname">말하는 감자</div>
            <div class="goal-title">주 3회 요가</div>
            <div class="goal-type">운동</div>
            <div class="cart-icon">
              <img
                src="{% static 'img/asset/Basket_alt_3.svg' %}"
                alt="Cart Icon"
              />
            </div>
          </div>
          <div class="goal-info">
            <img
              src="{% static 'img/asset/woman-2573216_1280 1.svg' %}"
              alt="주 3회 요가 Image"
            />
            <div class="goal-details">
              <div class="first-line">
                <span class="highlight">일주일에</span>
                <span>3회</span>
              </div>
              <div class="second-line">
                <p>1회당 1시간 30분 소요</p>
              </div>
            </div>
          </div>
          <hr />
          <div class="goal-actions">
            <button>
              <a href="{% url 'users:review' %}">
                리뷰 확인하기
              </a>
            </button>
            <button>
              <a href="{% url 'users:qna' %}">
                Q&A
              </a>
            </button>
          </div>
        </div>
        <div class="goal-card" data-category="식단">
          <div class="goal-header">
            <div class="logo-background">
              <img src="{% static 'img/asset/Logo2 1.svg' %}" alt="Goal Icon" />
            </div>
            <div class="goal-nickname">꿀고구마</div>
            <div class="goal-title">삼시세끼 알맞게 챙겨먹기</div>
            <div class="goal-type">식단</div>
            <div class="cart-icon">
              <img
                src="{% static 'img/asset/Basket_alt_3.svg' %}"
                alt="Cart Icon"
              />
            </div>
          </div>
          <div class="goal-info">
            <img
              src="{% static 'img/asset/image 4.svg' %}"
              alt="삼시세끼 알맞게 챙겨먹기 Image"
            />
            <div class="goal-details">
              <div class="first-line">
                <span class="highlight">하루에</span>
                <span>3회</span>
              </div>
              <div class="second-line">
                <p>아침: 오전 7시</p>
                <p>점심: 오후 12시</p>
                <p>저녁: 오후 6시</p>
                <p>1700kcal 전후로 너무 적거나 많지 않게 식사</p>
              </div>
            </div>
          </div>
          <hr />
          <div class="goal-actions">
            <button onclick="window.location.href='review.html'">
              리뷰 확인하기
            </button>
            <button
              onclick="window.location.href='q&a.html?goal=삼시세끼 알맞게 챙겨먹기'"
            >
              Q&A
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

goalGrove/users/templates/users/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GoalGrove 회원가입</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css">
    <link rel="stylesheet" href="{% static 'css/loginstyles.css' %}">
    <script src="{% static 'js/app.js' %}"></script>
</head>
<body>
    <div class="container">
        <div class="logo-container">
            <img src="{% static 'img/logo_shadow.svg' %}" alt="GoalGrove 로고" class="logo">
            <p class="description">
                <span>GoalGrove</span>에서 목표를 세우고 공유하며<br>주체적 성장을 시작하세요.
            </p>
        </div>
        <div class="main-content">
            <div class="signup-container">
                <h2>회원가입</h2>
                <form id="signupForm" method="post" novalidate>
                    {% csrf_token %}
                    <label for="id_username">아이디</label>
                    <input type="text" name="username" id="signupUsername" placeholder="영문 소문자, 숫자 포함 4~12자리" onblur="checkUsername()" required>
                    <div id="usernameCheckResult" class="check-result"></div>
                    <label for="id_password1">비밀번호</label>
                    <input type="password" name="password1" id="signupPassword" placeholder="영문 대/소문자, 숫자, 특수문자 포함 8~16자" required>
                    <label for="id_password2">비밀번호 재입력</label>
                    <input type="password" name="password2" id="signupConfirmPassword" required>
                    <label for="id_email">이메일</label>
                    <input type="email" name="email" id="signupEmail" placeholder="example@example.com" required>
                    <label for="id_nickname">닉네임</label>
                    <input type="text" name="nickname" id="signupName" onblur="checkNickname()" required>
                    <div id="nicknameCheckResult" class="check-result"></div>
                    <button type="submit">회원가입하기</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>